# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Collection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OAuthSwift'
  pod 'TTTAttributedLabel' 

  # Pods for Collection

  target 'CollectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CollectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
